/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ContentFooter: typeof import('./src/components/ContentFooter.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    InputField: typeof import('./src/components/InputField.vue')['default']
    MobileMenu: typeof import('./src/components/MobileMenu.vue')['default']
    ProcessingIndicator: typeof import('./src/components/ProcessingIndicator.vue')['default']
    ResultsDisplay: typeof import('./src/components/ResultsDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemChart: typeof import('./src/components/SystemChart.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    UploadArea: typeof import('./src/components/UploadArea.vue')['default']
  }
}
