/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about/History': RouteRecordInfo<'/about/History', '/about/History', Record<never, never>, Record<never, never>>,
    '/about/MissionVision': RouteRecordInfo<'/about/MissionVision', '/about/MissionVision', Record<never, never>, Record<never, never>>,
    '/Guide': RouteRecordInfo<'/Guide', '/Guide', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/legal/PrivacyPolicy': RouteRecordInfo<'/legal/PrivacyPolicy', '/legal/PrivacyPolicy', Record<never, never>, Record<never, never>>,
    '/legal/TermsConditions': RouteRecordInfo<'/legal/TermsConditions', '/legal/TermsConditions', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/support/ContactForm': RouteRecordInfo<'/support/ContactForm', '/support/ContactForm', Record<never, never>, Record<never, never>>,
    '/support/Feedback': RouteRecordInfo<'/support/Feedback', '/support/Feedback', Record<never, never>, Record<never, never>>,
    '/support/HelpFAQ': RouteRecordInfo<'/support/HelpFAQ', '/support/HelpFAQ', Record<never, never>, Record<never, never>>,
    '/user/auth/Login': RouteRecordInfo<'/user/auth/Login', '/user/auth/Login', Record<never, never>, Record<never, never>>,
    '/user/auth/Register': RouteRecordInfo<'/user/auth/Register', '/user/auth/Register', Record<never, never>, Record<never, never>>,
    '/user/Documents': RouteRecordInfo<'/user/Documents', '/user/Documents', Record<never, never>, Record<never, never>>,
    '/user/profile/Dashboard': RouteRecordInfo<'/user/profile/Dashboard', '/user/profile/Dashboard', Record<never, never>, Record<never, never>>,
    '/user/profile/Profile': RouteRecordInfo<'/user/profile/Profile', '/user/profile/Profile', Record<never, never>, Record<never, never>>,
  }
}
