services:
  api-go:
    build: ./backend
    env_file: ./backend/docker.env
    ports:
      - '8081:8081'

  api-ml:
    build: ./ml-api
    ports:
      - '5001:5001'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - api-go
      - api-ml